language: node_js

node_js:
    - 12.18.0

cache:
    yarn: true
    directories:
        - ~/.npm
        - ~/.cache
        - node_modules

install:
    - yarn --frozen-lockfile

scripts:
    - yarn lint
    - yarn build
    - yarn test:ci
